{"name": "test_zero_division_error", "status": "broken", "statusDetails": {"message": "ZeroDivisionError: division by zero", "trace": "self = <test_example.TestExampleError testMethod=test_zero_division_error>\n\n    def test_zero_division_error(self):\n        \"\"\"Test qui gÃ©nÃ¨re une erreur de division par zÃ©ro.\"\"\"\n>       return 1 / 0\nE       ZeroDivisionError: division by zero\n\nexamples\\test_example.py:51: ZeroDivisionError"}, "description": "Test qui gÃ©nÃ¨re une erreur de division par zÃ©ro.", "start": 1744388741213, "stop": 1744388741214, "uuid": "5d6334ce-982e-4950-8bd3-6f46382d2ae8", "historyId": "9262db0893ce797c78e8b75113cded7a", "testCaseId": "9262db0893ce797c78e8b75113cded7a", "fullName": "examples.test_example.TestExampleError#test_zero_division_error", "labels": [{"name": "parentSuite", "value": "examples"}, {"name": "suite", "value": "test_example"}, {"name": "subSuite", "value": "TestExampleError"}, {"name": "host", "value": "DESKTOP-ORG3GN0"}, {"name": "thread", "value": "18216-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "examples.test_example"}]}