{"name": "test_zero_division_error", "status": "broken", "statusDetails": {"message": "ZeroDivisionError: division by zero", "trace": "self = <test_example.TestExampleError testMethod=test_zero_division_error>\n\n    def test_zero_division_error(self):\n        \"\"\"Test qui génère une erreur de division par zéro.\"\"\"\n>       return 1 / 0\nE       ZeroDivisionError: division by zero\n\nexamples\\test_example.py:51: ZeroDivisionError"}, "description": "Test qui génère une erreur de division par zéro.", "start": 1744388816020, "stop": 1744388816021, "uuid": "a84bbe96-196e-477b-b138-2a8b8e9e26b5", "historyId": "9262db0893ce797c78e8b75113cded7a", "testCaseId": "9262db0893ce797c78e8b75113cded7a", "fullName": "examples.test_example.TestExampleError#test_zero_division_error", "labels": [{"name": "parentSuite", "value": "examples"}, {"name": "suite", "value": "test_example"}, {"name": "subSuite", "value": "TestExampleError"}, {"name": "host", "value": "DESKTOP-ORG3GN0"}, {"name": "thread", "value": "2352-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "examples.test_example"}]}