Vérification de la connexion à n8n (http://localhost:5678)... Échec de connexion!
Erreur: HTTPConnectionPool(host='localhost', port=5678): Max retries exceeded with url: /api/v1/workflows (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019AEB227350>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
problem in development\scripts\python\utils\project_utils\list_n8n_workflows.py - SystemExit: 1
